# Generated by Django 3.1.1 on 2020-09-03 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20200903_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='user2',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='invited_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
