# Generated by Django 3.1.1 on 2020-09-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200903_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsessionmessage',
            old_name='message',
            new_name='text',
        ),
        migrations.DeleteModel(
            name='ChatSessionMember',
        ),
    ]
