# Generated by Django 3.1.1 on 2020-09-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200905_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmessage',
            name='image',
            field=models.ImageField(null=True, upload_to='chat/'),
        ),
    ]
