# Generated by Django 3.1.1 on 2020-09-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200906_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsessionmessage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='chat/'),
        ),
    ]
