# Generated by Django 3.1.1 on 2020-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200906_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsessionmessage',
            name='image',
            field=models.ImageField(default='images/no-img.jpg', null=True, upload_to='images/'),
        ),
    ]
