# Generated by Django 3.1.1 on 2020-09-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200906_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsessionmessage',
            name='image',
            field=models.ImageField(null=True, upload_to='chat/'),
        ),
    ]
