# Generated by Django 3.1.1 on 2020-09-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20200906_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmessage',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsessionmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
